export const LABOR_REWARD_EMAIL = 'LABOR_REWARD_EMAIL';
export const CREATE_EMPLOYEE_EMAIL = 'CREATE_EMPLOYEE_EMAIL';
export const ADD_EDIT_USER = 'ADD_EDIT_USER';
export const E_RECEIPT_CREATE = 'E_RECEIPT_CREATE';
